version: "3.8"

services:
    database:
        image: mariadb:latest
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: moflix
            MYSQL_PASSWORD: 123
        ports:
            - "8000:3306"
        volumes:
            # - db_data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        healthcheck:
            interval: 5s
            retries: 3
            test:
                [
                    "CMD",
                    "healthcheck.sh",
                    "docker-entrypoint.sh",
                ]
            timeout: 30s

    recommender:
        build:
            context: ./recommender_server/recommender
            dockerfile: Dockerfile
        container_name: recommender
        environment:
            DB_HOST: "database"
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: 123
            DB_NAME: moflix
        ports:
            - "2000:8000"
        depends_on:
            - database

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        environment:
            DB_HOST: "database"
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: 123
            DB_NAME: moflix
            ML_SERVER_URL: "/recommender/contentbased"
            ML_SERVER_PORT: 8000
        ports:
            - "8080:8080"
        depends_on:
            - database
        # Bạn có thể thêm wait-for-it hoặc dockerize để đảm bảo MariaDB đã sẵn sàng trước khi backend khởi động

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "3000:3000"
        depends_on:
            backend:
                condition: service_started

volumes:
    db_data:
